# Generated by Django 3.1.4 on 2020-12-31 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_logged_in', models.DateTimeField(null=True)),
                ('first_name', models.CharField(max_length=16, null=True)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('date_of_birth', models.DateField(max_length=40, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('profile_picture', models.FileField(null=True, upload_to='files')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_logged_in', models.DateTimeField(null=True)),
                ('first_name', models.CharField(max_length=16, null=True)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('date_of_birth', models.DateField(max_length=40, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('profile_picture', models.FileField(null=True, upload_to='files')),
                ('commission', models.FloatField(null=True)),
                ('scheduled_rides', models.IntegerField(null=True)),
                ('unscheduled_rides', models.IntegerField(null=True)),
                ('total_rides', models.IntegerField(null=True)),
                ('documentation', models.FileField(null=True, upload_to='files')),
                ('license_issue_date', models.DateField(null=True)),
                ('license_expiry_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carMake', models.CharField(max_length=40, null=True)),
                ('carModel', models.CharField(max_length=200, null=True)),
                ('carCapacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('time', models.TimeField(null=True)),
                ('numPassengers', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending Pickup', 'Pending Pickup'), ('Pickup Location', 'Pickup Location'), ('Pending Drop-off', 'Pending Drop-off'), ('Drop-off Location', 'Drop-off Location')], max_length=200, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.client')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driver')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.location')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vehicle'),
        ),
    ]
