# Generated by Django 3.1.4 on 2021-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
