# Generated by Django 3.1.4 on 2021-01-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210101_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='location',
        ),
        migrations.AddField(
            model_name='ride',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_location', to='dashboard.location'),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_location', to='dashboard.location'),
        ),
    ]
