# Generated by Django 3.1.4 on 2021-01-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210103_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='profile_picture',
        ),
    ]
