# Generated by Django 3.1.4 on 2021-01-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210103_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('Scheduled Ride', 'Scheduled Ride'), ('Unscheduled Ride', 'Unscheduled Ride')], max_length=200, null=True),
        ),
    ]
